### ISSUE TITLE
有错误

### ISSUE THREAD

**Issue by flyftfy** [rozbo/node-noss#4]
报错了。。
![image](https://github.com/rozbo/node-noss/assets/152277380/be174334-55e1-4d52-9e77-6faab1453d95)

**Comment by QuantumLeap-us** [comment]
同样得 跑不起
![image](https://github.com/rozbo/node-noss/assets/40482494/2e8cae25-d20f-45df-b3ad-5d139203f0cb)

**Comment by rozbo** [comment]
修复了， https://github.com/rozbo/node-noss/issues/2，
重新pnpm install 即可
